### ISSUE TITLE
iPadOS 15.1 

### ISSUE THREAD

**Issue by LlewAdamson-test** [XITRIX/iTorrent#209]
App not opening after yesterday's iPadOS update.

**Comment by hritvikpatel4** [comment]
Yes, this is because the app currently does not support iOS/iPadOS 15.X

**Comment by XITRIX** [comment]
Download ipa from [AppCenter](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public), it was fixed for iOS 15

**Comment by LlewAdamson-test** [comment]
Hi, I've tried Version 1.8.4-dev.3 (21.0) and it doesn't work for iPadOS 15.1

**Comment by CHEN1016** [comment]
l have update the version 1.8.4-dev.3 (21.0) (update at Sep 26, 2021 at 17:41 in AppCenter), but it still crash in IOS15.1

**Comment by XITRIX** [comment]
I've just reinstall iTorrent from AppCenter link on my iPad Pro with iOS 15.1, works without any problem. Try to clean _Config folder in Files app.

**Comment by CHEN1016** [comment]
@XITRIX This may be the altstore problem, I've update altstore and it work fine

**Comment by hritvikpatel4** [comment]
@CHEN1016 how did you update the altstore? I went to the appcenter.ms link in the README and then installed the app from there (v1.8.4-dev.3 (21.0)) but it gives me error saying “could not validate the integrity of the app”

details:
iOS 15.1
iPhone 13 Pro
iPhone XS

It doesn’t work on either of those phones
@XITRIX 

![B3B76589-EE06-45C4-B374-E18FBCCFD879](https://user-images.githubusercontent.com/36025028/139177028-4ba61669-535e-4f0e-82e4-b202906b635e.jpeg)

**Comment by CHEN1016** [comment]
@hritvikpatel4 Just reinstall altstore by altserver, they have updated the altstore version to 1.4.7, make sure that your altserver version is 1.4.7

**Comment by XITRIX** [comment]
@hritvikpatel4, AppCenter link is not supposed to be used directly from device, in case device is not jailbroken with AppSync installed. You should download an ipa file file from an AppCenter (to have such option, open website in desktop mode) and install it with any available method (AltStore is best option)

**Comment by hritvikpatel4** [comment]
@XITRIX yes i was finally able to install it on my device using altserver. Thanks!

**Comment by XITRIX** [comment]
You are welcome! :)
